version: 2.1

orbs:
  secret-injector: bestsellerit/secret-injector@0.2.32

commands:
  goreleaser:
    parameters:
      release-type:
        type: string
    steps:
      - run:
          name: Install GoReleaser
          command: |
            go install github.com/goreleaser/goreleaser@latest
      - run:
          name: Import private key
          command: |
            source /tmp/secrets.env
            echo -e "$GPG_PRIVATE_KEY" | base64 --decode > $HOME/private.key
            gpg --pinentry-mode loopback --batch --yes --import $HOME/private.key
      - run:
          name: Run GoReleaser
          command: |
            source /tmp/secrets.env

            if [ "<< parameters.release-type >>" = "test" ] ; then
              goreleaser release --snapshot --clean
            else
              goreleaser release --clean
            fi

jobs:
  build:
    parameters:
      release-type:
        type: enum
        enum: ["test", "release"]
        default: "test"
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - goreleaser:
          release-type: << parameters.release-type >>


tag_filter: &tag_filter /v[0-9]+.[0-9]+.[0-9]+/
my_context: &my_context es02-prod

dump_secrets: &dump_secrets
  vault-path: ES/terraform-provider/prod
  output-type: env

test_filter: &test_filter
  filters:
    tags:
      ignore: *tag_filter
release_filter: &release_filter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: *tag_filter

workflows:
  tester:
    jobs:
      - secret-injector/dump-secrets:
          <<: *dump_secrets
          context: *my_context
          <<: *test_filter
      - build:
          release-type: test
          name: test
          requires:
            - secret-injector/dump-secrets
          <<: *test_filter
  build-n-release:
    jobs:
      - secret-injector/dump-secrets:
          <<: *dump_secrets
          context: *my_context
          <<: *release_filter
      - build:
          name: build
          release-type: release
          requires:
            - secret-injector/dump-secrets
          <<: *release_filter
