version: 2.1

orbs:
  secret-injector: bestsellerit/secret-injector@0.2.32


jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: go get
          command: |
            go get -v ./...
      - run:
          name: Go Releaser
          command: |
            source /tmp/secrets.env

            echo -e "$GPG_PRIVATE_KEY" | base64 --decode > private.key
            gpg --pinentry-mode loopback --batch --yes --import private.key

            curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
            ./bin/goreleaser release --snapshot --rm-dist

workflows:
  version: 2
  build-n-release:
    jobs:
      - secret-injector/dump-secrets:
          vault-path: ES/terraform-stuff/dev
          output-type: env
          context: es02-dev
      - build:
          requires:
            - secret-injector/dump-secrets
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+/
