version: 2.1

orbs:
  secret-injector: bestsellerit/secret-injector@0.2.32

commands:
  goreleaser:
    parameters:
      release-type:
        type: string
    steps:
      - run:
          name: Install GoReleaser
          command: |
            curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
            sudo mv ./bin/goreleaser /usr/bin/goreleaser
            rm -rf ./bin
      - run:
          name: Import private key
          command: |
            source /tmp/secrets.env
            echo -e "$GPG_PRIVATE_KEY" | base64 --decode > $HOME/private.key
            gpg --pinentry-mode loopback --batch --yes --import $HOME/private.key
      - run:
          name: Run GoReleaser
          command: |
            source /tmp/secrets.env

            if [ "<< parameters.release-type >>" = "test" ] ; then
              goreleaser release --snapshot --rm-dist
            else
              goreleaser release --rm-dist
            fi

jobs:
  build:
    parameters:
      release-type:
        type: enum
        enum: ["test", "release"]
        default: "test"
    docker:
      - image: circleci/golang:1.14
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:
          name: go get
          command: |
            go get -v ./...
      - goreleaser:
          release-type: << parameters.release-type >>

workflows:
  version: 2
  tester:
    jobs:
      - secret-injector/dump-secrets:
          vault-path: ES/terraform-stuff/dev
          output-type: env
          context: es02-dev
          filters:
            tags:
              ignore: /v[0-9]+.[0-9]+.[0-9]+/
      - build:
          release-type: test
          requires:
            - secret-injector/dump-secrets
          filters:
            tags:
              ignore: /v[0-9]+.[0-9]+.[0-9]+/
  build-n-release:
    jobs:
      - secret-injector/dump-secrets:
          vault-path: ES/terraform-stuff/dev
          output-type: env
          context: es02-dev
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+/
      - build:
          release-type: release
          requires:
            - secret-injector/dump-secrets
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+.[0-9]+.[0-9]+/
